[tool.isort]
profile = "black"
src_paths = ["lenny"]

[tool.black]
line-length = 128

[tool.pyright]
include = ["lenny", "test"]
exclude = ["**/__pycache__"]
extraPaths = ["lenny"]
typeCheckingMode = "strict"
