name: LINTING

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "pyproject.toml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail_level: error
          flake8_args: "--ignore=W503 --max-line-length=999 src test"

  black-lints:
    runs-on: ubuntu-latest
    name: black
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Black linter
        uses: reviewdog/action-black@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          black_args: "--check --verbose src test"
