name: Python Unit Tests & Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - &checkout_step
        name: Check out source repository
        uses: actions/checkout@v4

      - &setup_python_step
        name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "W503"
          max-line-length: 999
          path: src test
          plugins: "flake8-black"

  black-lints:
    runs-on: ubuntu-latest
    name: black
    steps:
      - *checkout_step
      - *setup_python_step

      - name: Black linter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: src

  unit-test:
    runs-on: ubuntu-latest
    name: pytest
    steps:
      - *checkout_step
      - *setup_python_step

      - &install-dependencies-step
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run unit-tests
        run: python -m pytest
