name: MAIN

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.bat"
      - ".env.example"
      - "./.github/**"
      - "cspell.json"
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.bat"
      - ".env.example"
      - "./.github/**"
      - "cspell.json"
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: pytest (GENERAL)
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup

      - name: Run pytest
        run: python -m pytest --ignore=test/bot_test.py

  unit-test-bot:
    runs-on: ubuntu-latest
    name: pytest (BOT)
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup

      - name: Run pytest on bot_test.py
        run: python -m pytest test/bot_test.py

  requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup

      - name: Install pip-check-reqs
        run: |
          pip install pip-check-reqs

      - name: Check for imports missing from requirements.txt
        run: pip-missing-reqs lenny test --ignore-file=requirements.txt

      - name: Check for unused packages in requirements.txt
        run: pip-extra-reqs lenny test --ignore-file=requirements.txt
