name: MAIN

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - uses: ./.github/actions/setup

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "W503"
          max-line-length: 999
          path: src test
          plugins: "flake8-black"

  black-lints:
    runs-on: ubuntu-latest
    name: black
    steps:
      - uses: ./.github/actions/setup

      - name: Black linter
        uses: psf/black@stable
        with:
          options: "--check --verbose src test"

  unit-test:
    runs-on: ubuntu-latest
    name: pytest
    steps:
      - uses: ./.github/actions/setup

      - name: Run unit-tests
        run: python -m pytest

  requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Install pip-check-reqs
        run: |
          pip install pip-check-reqs

      - name: Check for unused requirements
        run: pip-missing-reqs src test --ignore-file=requirements.txt || true

      - name: Check for missing requirements
        run: pip-extra-reqs src test --ignore-file=requirements.txt || true
