name: Python Unit Tests & Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    name: Initialise Container
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"

  requirements:
    name: Install Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

  flake8-lint:
    needs: setup
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "W503"
          max-line-length: 999
          path: src test
          plugins: "flake8-black"

  black-lints:
    needs: setup
    runs-on: ubuntu-latest
    name: black
    steps:
      - name: Black linter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: src

  unit-test:
    needs: [setup, requirements]
    runs-on: ubuntu-latest
    name: pytest
    steps:
      - name: Run unit-tests
        run: python -m pytest

  check-unused-requirements:
    needs: [setup, requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pip-check-reqs
        run: pip install pip-check-reqs
      - name: Check for unused requirements
        run: |
          pip-missing-reqs . --ignore-file=requirements.txt || true
