name: SPELLCHECK

on:
  push:
    branches: [main]
    paths:
      - "readme.md"
      - "assets/locales/en.json" # cspell config is set to english only
  pull_request:
    paths:
      - "readme.md"
      - "assets/locales/en.json" # cspell config is set to english only
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install cspell
        run: npm install -g cspell

      - name: Run spell check
        run: cspell --config cspell.json readme.md assets/locales/en.json
