name: SPELLCHECK

on:
  push:
    branches: [main]
    paths-ignore:
      - "./submodules/**"
      - "./temp/**"
    paths:
      - "*.md"
      - "*.py"
      - "cspell.json"
      - "./.github/workflows/spellcheck.yml"
  pull_request:
    paths-ignore:
      - "./submodules/**"
      - "./temp/**"
    paths:
      - "*.md"
      - "*.py"
      - "cspell.json"
      - "./.github/workflows/spellcheck.yml"
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install cspell
        run: npm install -g cspell

      - name: Run spell check
        run: cspell --config cspell.json "./src/**/*.py" "*.md"
