name: SPELLCHECK

on:
  push:
    branches: [main]
    paths:
      - "readme.md"
  pull_request:
    paths:
      - "readme.md"
      - "**/*.py"
      - "cspell.json"
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install cspell
        run: npm install -g cspell

      - name: Run spell check
        run: cspell --config cspell.json lenny/**/*.py lenny/*.py test/**/*.py test/*.py readme.md
