name: SPELLCHECK

on:
  push:
    branches: [main]
    paths:
      - "readme.md"
      - "src/**/*.py"
      - "test/**/*.py"
      - "cspell.json"
      - ".github/**"
  pull_request:
    paths:
      - "readme.md"
      - "src/**/*.py"
      - "test/**/*.py"
      - "cspell.json"
      - ".github/**"
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install cspell
        run: npm install -g cspell

      - name: Run spell check - Source files
        run: cspell --config cspell.json src/**/*.py

      - name: Run spell check - Test files
        run: cspell --config cspell.json test/**/*.py

      - name: Run spell check - Readme
        run: cspell --config cspell.json readme.md
